name: "Destroy Terraform Workspace"

on: 
  push:
    branches:
      - master
jobs:
  get_workspace:
    name: Get Workspace
    runs-on: ubuntu-latest
    steps:
      - name: print envs
        run: echo $(env)